### ISSUE TITLE
linux build missing BGRABitmapPack

### ISSUE THREAD

**Issue by ftoledo** [codewar65/VTXEdit#1]
Hi! 
i try to build it on linux. (i have no experience on use fpc or lazarus) 

![pantallazo-2017-09-25 11-11-34](https://user-images.githubusercontent.com/95441/30817374-12b00bee-a1ef-11e7-8269-0afde27512d5.png)

I open the lazarus project, and i see  that dependencie missing BGRABitmapPack, 
need i built it previously, true?

**Comment by codewar65** [comment]
TBGRABitmap package is required. 
See http://wiki.freepascal.org/BGRABitmap for more information.
